### ISSUE TITLE
thanks man

### ISSUE THREAD

**Issue by wintermute-cell** [Thrilleratplay/node-jsonlz4-decompress#4]
Hey! hope you read this, since this repo is pretty old.

today I accidentally `rm -rf`'d all the dotfiles in my home directory. 
no biggie I thought, I have all my dotfiles in a git remote. 
EXCEPT FOR the `.mozilla` directory containing my bookmarks (which I have accumulated over 4 or so years).

after recovering all the non-overwritten data I could, the database file that should contain my bookmarks was nowhere to be found. all that I was able to gather after a couple hours of searching were a bunch of unreadable and broken backup files in mozlz4 format.

But no implementation of the format could read the compressed files, since they were incomplete and had holes.
But then, after trying out so many programs and libs, I found your implementation, and I don't know why, but it was able to spit out 99% of the decompressed data before crashing due to the broken file!!

for that I'd like to thank you man, and If thats ok for you and you have a donation link or paypal or something like that, I'd like to send you $5 for saving my ass <3

**Comment by Thrilleratplay** [comment]
@wintermute-cell I made this years ago to save my own ass.  I'm not sure why this implantation worked while others didn't but I'm glad you found it useful.  Hopefully you learned a valuable lesson about backups.  

This thank you is more than enough of a payment.  If you have $5 burning a hole in your pocket, donate it to a worthy cause like the [EFF](https://www.eff.org/).

**Comment by wintermute-cell** [comment]
for a worthy cause it is then. 
thanks again, without you I wouldn't be as happy as I am right now! :)
